#
# This source file is part of the Neurodevelopment Assessment and Monitoring System (NAMS) project
#
# SPDX-FileCopyrightText: 2023 Stanford University
#
# SPDX-License-Identifier: MIT
#

name: Test Checkout

on:
  pull_request:
  workflow_dispatch:
  workflow_call:

jobs:
  checkout:
    name: Test recursive checkout
    runs-on: ubuntu-latest
    steps:
      - name: Checkout with submodules
        uses: actions/checkout@v4
        with:
          submodules: true
